name: x402_dart
description: Workspace for the x402 protocol that supports multiple blockchains.
repository: https://github.com/minhqdao/x402-dart
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/x402
  - packages/x402_core
  - packages/x402_evm
  - packages/x402_svm
  - examples/client_wrapper
  - examples/client_manual

dev_dependencies:
  lint: ^2.8.0
  melos: ^7.3.0

melos:
  scripts:
    analyze:
      description: Analyze all packages in this workspace.
      run: melos exec -- dart analyze --fatal-infos --fatal-warnings
    test:
      description: Run all tests in this workspace.
      run: melos exec --dir-exists=test -- dart test
