name: x402_workspace
description: Workspace for the x402 protocol that supports multiple blockchains.
repository: https://github.com/minhqdao/x402
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - examples/client_evm
  - examples/client_manual_handshake
  - examples/client_svm
  - examples/client_wrapper
  - examples/server_evm
  - examples/server_svm
  - examples/facilitator
  - packages/x402
  - packages/x402_core
  - packages/x402_evm
  - packages/x402_svm

dev_dependencies:
  lint: ^2.8.0
  melos: ^7.3.0

melos:
  scripts:
    test:
      description: Run all tests in this workspace.
      run:  melos exec --dir-exists=test -- dart test
