name: client_svm
description: x402 SVM Client Example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  solana: ^0.32.0
  x402:

dev_dependencies:
  lint: ^2.8.0
