name: x402_svm
description: SVM blockchain implementation of the x402 protocol.
version: 0.1.0
repository: https://github.com/minhqdao/x402
homepage: https://github.com/minhqdao/x402
issue_tracker: https://github.com/minhqdao/x402/issues

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  convert: ^3.1.2
  http: ^1.6.0
  solana: ^0.32.0
  x402_core: ^0.1.0

dev_dependencies:
  lint: ^2.8.0
  mocktail: ^1.0.4
  test: ^1.29.0
