name: client_wrapper
description: x402 Client Wrapper Example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dotenv: ^4.2.0
  http: ^1.1.0
  web3dart: ^2.7.3
  x402:

dev_dependencies:
  lint: ^2.8.0
