name: x402_example_client
description: A simple client demonstrating x402 payment protection.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  solana: ^0.32.0
  web3dart: ^2.7.3
  x402:

dev_dependencies:
  lint: ^2.0.0