name: client_manual
description: x402 Manual Client Example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  http: ^1.1.0
  x402:

dev_dependencies:
  lint: ^2.8.0
