name: client_manual
description: x402 Manual Client Example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  dotenv: ^4.2.0
  http: ^1.6.0
  x402:

dev_dependencies:
  lint: ^2.8.0
