name: x402
description: Unified package for the x402 protocol with support for multiple blockchains.
version: 0.1.0
repository: https://github.com/minhqdao/x402
homepage: https://github.com/minhqdao/x402
issue_tracker: https://github.com/minhqdao/x402/issues
topics:
  - x402
  - payment
  - web3
  - blockchain
  - http

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  x402_core: ^0.1.0
  x402_evm: ^0.1.0
  x402_svm: ^0.1.0

dev_dependencies:
  lint: ^2.8.0
