name: CI
on: push

jobs:
    format_analyze_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: bluefireteam/melos-action@v3
            - run: melos format --set-exit-if-changed
            - run: melos analyze
            - run: melos test
